### ISSUE TITLE
Go Module Support?

### ISSUE THREAD

**Issue by cgilling** [newrelic/go-insights#10]
Is this something your folks are interested in? If so I could do a PR.

**Comment by jthurman42** [comment]
I have a branch with go.mod support for this, but never pushed it.  We have started consolidating the Go libraries for NR into a single repo ( https://github.com/newrelic/newrelic-client-go ), and this is eventually on the list to go there as well so little work has been done in this repo while in that process.  The only caveat to go.mod is that golangci-lint is broken...

**Comment by cgilling** [comment]
Good to know about the `newrelic-client-go` repo, funnily enough I recently wrote my own client internally to manage new relic alerts, I guess I should migrate over at some point.

There were a couple of other things I was hoping to improve with the client library (such as properly flushing all worker goroutines when flush is called). Since this library will be migrated in the not too distant future is that something that you would still want contributed back or should I just maintain my own fork?

**Comment by jthurman42** [comment]
Resolved in #11

**Comment by jthurman42** [comment]
For additional work, contributing back here would be great as the timeline for consolidation hasn't been established yet.  We're working on a few other priorities at the moment.  If you are curious around that work, we have an RFC that we would love feedback on for our Developer Toolkit public roadmap: https://discuss.newrelic.com/t/rfc-developer-toolkit-roadmap-2020/90528
