### ISSUE TITLE
Proxy server support

### ISSUE THREAD

**Issue by psomareddy** [newrelic/go-insights#3]
Does the go-insights library support (forwarding) proxy?

**Comment by jthurman42** [comment]
Yes, the actual POST mechanism uses the Golang net/http client which supports a proxy, and will automatically load the configuration from the environment.

Before launching your application make sure that either HTTP_PROXY or HTTPS_PROXY environment variable is set.  There is NO direct configuration for the client itself.

Internal POST code: https://github.com/newrelic/go-insights/blob/master/client/insert.go#L320

net/http Proxy info: https://golang.org/pkg/net/http/#ProxyFromEnvironment
